services:
  app:
    container_name: familyTreeAPI
    build: .
    environment:
      PORT: 3000
      MONGO_URL: mongodb://mongodb:27017/family_tree
    ports:
      - '3000:3000'
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
volumes:
  mongodata:
